### ISSUE TITLE
Table doesn't show correctly in GitHub due to problematic priority of | over `

### ISSUE THREAD

**Issue by CherryDT** [rprichard/win32-console-docs#2]
![image](https://cloud.githubusercontent.com/assets/6010463/25288884/0251cafc-26d0-11e7-83b0-a9842e1cd0ff.png)

**Comment by rprichard** [comment]
Thanks for letting me know.  I've worked around the problem by replacing "`FOO | BAR`" with "`FOO` and `BAR`".  I prefer the original syntax, but this is easier.  My guess is that the change was undesired, and it's a regression in GitHub's Markdown processing.

This issue is interesting: https://github.com/erusev/parsedown/issues/184.  The Markdown in the bug report does the same thing I did, and it doesn't work.  But then the issue is fixed, and if you paste the bug report's Markdown into http://parsedown.org/demo, it works as expected.

**Comment by rprichard** [comment]
This is probably more relevant, https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown.

I suspect the change was intentional.  Apparently the proper fix is:
```
`FOO \| BAR`
```


> Include a pipe in a cell’s content by escaping it, including inside other inline spans:
>
> Example 191
>
> ```
> | f\|oo  |
> | ------ |
> | b `\|` az |
> | b **\|** im |
> ```



https://github.github.com/gfm/

I see that Parsedown will mishandle this fix, but I haven't found any evidence that GitHub ever used Parsedown.
